# Generated by Django 5.1.3 on 2024-11-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arearesult',
            old_name='date',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='categoryresult',
            old_name='date',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='focus',
            old_name='date',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='questionresult',
            old_name='date',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='date',
            new_name='completion_time',
        ),
        migrations.RenameField(
            model_name='surveycompletion',
            old_name='survey_date',
            new_name='completion_time',
        ),
    ]
