# Generated by Django 5.1.3 on 2024-11-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0002_alter_area_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
