# Generated by Django 5.1.3 on 2024-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0002_rename_date_arearesult_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='formula',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='formula',
            field=models.CharField(max_length=1000),
        ),
    ]
