# Generated by Django 5.1.3 on 2024-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0003_remove_question_name_alter_question_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='focus',
            options={'verbose_name_plural': 'Focus'},
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='version',
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='max_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arearesult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='categoryresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
