# Generated by Django 5.1.4 on 2024-12-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0003_alter_area_formula_alter_category_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focus',
            name='esthetic_focus',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='lifestyle_focus',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='skincare_focus',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='AreaResult',
        ),
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
