# Generated by Django 5.1.3 on 2024-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0004_alter_category_options_alter_focus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alphabetic_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
